@startuml EstimaDevSequenceDiagram

!define CONTROLLER participant
!define SERVICE participant
!define DOMAIN participant
!define ACTOR actor
!define DATABASE database

title EstimaDev - Diagrama de Sequência

actor Desenvolvedor
participant UsuarioController
participant UsuarioService
participant UsuarioRepository
participant BancoDeDados

Desenvolvedor -> UsuarioController : Listar Todos
UsuarioController -> UsuarioService : ListarTodos()
UsuarioService -> UsuarioRepository : ObterTodos()
UsuarioRepository -> BancoDeDados : Consulta SQL
BancoDeDados --> UsuarioRepository : Dados de Usuários
UsuarioRepository --> UsuarioService : Usuários
UsuarioService --> UsuarioController : Usuários
UsuarioController --> Desenvolvedor : Resposta

@enduml
